#!/usr/bin/env ruby
require 'date'

class Student
  @@students = []
  attr_accessor :name, :surname, :date_of_birth

  def initialize(name, surname, date_of_birth)
    @name = name
    @surname = surname
    @date_of_birth = date_of_birth

    raise ArgumentError, "Wrong date of birth" unless correct_date?
    add_student
  end

  def self.all_students
    @@students
  end

  def correct_date?
    @date_of_birth.is_a?(Date) && @date_of_birth < Date.today
  end

  def student_duplicate?
    @@students.any? do |student|
      student.name == @name && student.surname == @surname && student.date_of_birth == @date_of_birth
    end
  end

  def calculate_age
    today = Date.today
    age = today.year - @date_of_birth.year
    age -= 1 if today.month < @date_of_birth.month || (today.month == @date_of_birth.month && today.day < @date_of_birth.day)
    age
  end

  def add_student
    raise ArgumentError, "Duplicate student" if student_duplicate?
    @@students << self
  end

  def self.remove_student(student)
    @@students.delete_if { |s| student.name == s.name && student.surname == s.surname && student.date_of_birth == s.date_of_birth }
  end

  def self.get_students_by_age(age)
    @@students.select { |student| student.calculate_age == age }
  end

  def self.get_students_by_name(name)
    @@students.select { |student| student.name == name }
  end
end

s1 = Student.new("Oleksandr", "Helevan", Date.new(2006,3,15))
Student.new("Volodymyr", "Dobryanskiy", Date.new(2005,12,12))
Student.new("Volodymyr", "Savtenko", Date.new(2006,2,23))
Student.new("Anton", "Olianyuk", Date.new(2006,3,15))
Student.new("Vlad", "Ostrovskiy", Date.new(2005,2,24))
Student.new("Volodymyr", "Zanlovskiy", Date.new(2006,4,23))
Student.new("Vasya", "Rusnak", Date.new(2006,7,29))

puts "--------------------------"
Student.get_students_by_age(18).each { |student| puts "#{student.name} #{student.surname} - #{student.calculate_age} years" }
puts "--------------------------"
Student.get_students_by_name("Volodymyr").each { |student| puts "#{student.name} #{student.surname}" }
puts "--------------------------"
Student.all_students.each_with_index { |student, index| puts "#{index+1}. #{student.name} #{student.surname}" }

Student.remove_student(s1)
puts "--------------------------"
Student.all_students.each_with_index { |student, index| puts "#{index+1}. #{student.name} #{student.surname}" }
